import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';

import { agentLabel, agentMetrics, agentStatus, confidenceBand, decisionPresentation, orderedAgents } from '../agentUtils';
import type { AgentDecision, CompletedRun } from '../types';
import { percent } from '../utils';

export function ExpectedWorkflowSkeleton() {
    const stages = ['Detection', 'Security assessment', 'Digital-twin evaluation', 'Planning', 'Trust assessment', 'Response assembly', 'Telemetry publication'];
    return <section className="panel expected-workflow" role="status"><span className="eyebrow">Expected processing sequence</span><h2>Simulation request in progress</h2><p>This is an expected workflow skeleton, not live agent telemetry.</p><ol>{stages.map((stage) => <li key={stage}>{stage}</li>)}</ol></section>;
}

export function AgentSummaryMetrics({ records }: { records: AgentDecision[] }) {
    const metrics = agentMetrics(records);
    return <section className="agent-summary" aria-label="Frontend-derived agent execution summary"><div><span>Agents executed</span><strong>{metrics.executed}</strong></div><div><span>Completed</span><strong>{metrics.completed}</strong></div><div><span>Warnings</span><strong>{metrics.warnings}</strong></div><div><span>Failed</span><strong>{metrics.failed}</strong></div><div><span>Human review</span><strong>{metrics.humanReview}</strong></div><div><span>Average confidence</span><strong>{metrics.averageConfidence === null ? 'Unavailable' : percent(metrics.averageConfidence)}</strong></div><div><span>Slowest agent</span><strong>{metrics.slowest ? agentLabel(metrics.slowest) : 'Not exposed'}</strong></div><div><span>Most conservative</span><strong>{metrics.conservative ? agentLabel(metrics.conservative) : 'Unavailable'}</strong></div><div><span>Total agent time</span><strong>{metrics.totalDurationMs === null ? 'Not exposed' : `${metrics.totalDurationMs.toFixed(3)} ms`}</strong></div><small>Aggregates are derived in the interface from backend execution records. Confidence bands are UI interpretations, not clinical thresholds.</small></section>;
}

export function AgentExecutionGraph({ records, selectedId, onSelect }: { records: AgentDecision[]; selectedId: string | null; onSelect: (record: AgentDecision) => void }) {
    const ordered = orderedAgents(records);
    return <section className="panel agent-graph" aria-labelledby="execution-graph-title"><div className="section-heading"><div><span className="eyebrow">Directed execution record</span><h2 id="execution-graph-title">Agent Execution Graph</h2></div></div>{ordered.length === 0 ? <div className="empty-state">No agent execution records were returned.</div> : <div className="agent-graph__flow">{ordered.map((record, index) => <div className="agent-graph__step" key={`${record.agent}-${record.sequence ?? index}`}><button type="button" aria-label={`Select ${agentLabel(record)}, ${agentStatus(record)}`} aria-pressed={(record.agent_id ?? record.agent) === selectedId} className={`agent-node agent-node--${agentStatus(record)} ${(record.agent_id ?? record.agent) === selectedId ? 'agent-node--selected' : ''}`} onClick={() => onSelect(record)}><span>{record.component_type === 'system' ? 'System step' : `Agent ${record.sequence ?? index + 1}`}</span><strong>{agentLabel(record)}</strong><small>{record.stage?.replaceAll('-', ' ') ?? 'Stage not exposed'}</small><b>{agentStatus(record).replaceAll('-', ' ')}</b><em>{percent(record.confidence)} · {confidenceBand(record.confidence)}</em>{record.human_review_required && <i>⚠ Human review</i>}</button>{index < ordered.length - 1 && <span className="agent-edge" aria-hidden="true">→</span>}</div>)}</div>}</section>;
}

export function AgentTimeline({ records, selectedId, onSelect }: { records: AgentDecision[]; selectedId: string | null; onSelect: (record: AgentDecision) => void }) {
    const [query, setQuery] = useState('');
    const [status, setStatus] = useState('all');
    const [sort, setSort] = useState<'sequence' | 'duration'>('sequence');
    const [expanded, setExpanded] = useState<Set<string>>(new Set());
    const visible = useMemo(() => orderedAgents(records).filter((record) => {
        const matchesQuery = `${agentLabel(record)} ${record.action}`.toLowerCase().includes(query.toLowerCase());
        return matchesQuery && (status === 'all' || agentStatus(record) === status);
    }).sort((left, right) => sort === 'duration' ? (right.duration_ms ?? -1) - (left.duration_ms ?? -1) : (left.sequence ?? 999) - (right.sequence ?? 999)), [records, query, status, sort]);
    const toggle = (id: string) => setExpanded((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
    return <section className="panel agent-timeline-panel"><div className="section-heading"><div><span className="eyebrow">Actual completed response records</span><h2>Execution Timeline</h2></div></div><div className="agent-filters"><label>Search<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Agent or action" /></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{['completed', 'warning', 'failed', 'skipped', 'human-review-required'].map((value) => <option value={value} key={value}>{value.replaceAll('-', ' ')}</option>)}</select></label><label>Sort<select value={sort} onChange={(event) => setSort(event.target.value as 'sequence' | 'duration')}><option value="sequence">Sequence</option><option value="duration">Duration</option></select></label></div>{visible.length === 0 ? <div className="empty-state">No execution records match these filters.</div> : <ol className="agent-timeline">{visible.map((record, index) => { const id = record.agent_id ?? record.agent; const isExpanded = expanded.has(id); const presentation = decisionPresentation(record.action); return <li key={`${id}-${index}`} className={(id === selectedId ? 'agent-timeline--selected' : '')}><button className="agent-timeline__select" type="button" onClick={() => onSelect(record)}><span>{record.sequence ?? '—'}</span><div><strong>{agentLabel(record)}</strong><small>{record.stage?.replaceAll('-', ' ') ?? 'Stage not exposed'}</small></div><b className={`agent-status agent-status--${agentStatus(record)}`}>{agentStatus(record).replaceAll('-', ' ')}</b><em>{presentation.label}</em><span>{percent(record.confidence)} · {confidenceBand(record.confidence)}</span><span>{record.duration_ms === null || record.duration_ms === undefined ? 'Not exposed by backend' : `${record.duration_ms.toFixed(3)} ms`}</span></button><button className="link-button" type="button" aria-expanded={isExpanded} onClick={() => toggle(id)}>{isExpanded ? 'Collapse' : 'Expand'} execution summary</button>{isExpanded && <p>{record.explanation}</p>}</li>; })}</ol>}</section>;
}

export function AgentDetailPanel({ record, run }: { record: AgentDecision | null; run: CompletedRun }) {
    if (!record) return <aside className="panel agent-detail"><div className="empty-state">Select an execution record to inspect its decision-support output.</div></aside>;
    const presentation = decisionPresentation(record.action);
    const evidence = run.result.evidence.filter((item) => record.evidence_ids?.includes(item.evidence_id));
    return <aside className="panel agent-detail" aria-live="polite"><span className="eyebrow">Selected execution record</span><h2>{agentLabel(record)}</h2><div className="agent-detail__badges"><span className={`agent-status agent-status--${agentStatus(record)}`}>{agentStatus(record).replaceAll('-', ' ')}</span><span>{percent(record.confidence)} · {confidenceBand(record.confidence)}</span>{record.component_type === 'system' && <span>System processing — not an agent</span>}</div><dl><div><dt>Purpose</dt><dd>{record.purpose ?? 'Not exposed by backend'}</dd></div><div><dt>Stage</dt><dd>{record.stage?.replaceAll('-', ' ') ?? 'Not exposed by backend'}</dd></div><div><dt>Decision</dt><dd>{presentation.label}</dd></div><div><dt>Decision rationale</dt><dd>{record.explanation}</dd></div><div><dt>Recommended next step</dt><dd>{presentation.nextStep}</dd></div><div><dt>Duration</dt><dd>{record.duration_ms === null || record.duration_ms === undefined ? 'Not exposed by backend' : `${record.duration_ms.toFixed(3)} ms`}</dd></div><div><dt>Human review</dt><dd>{record.human_review_required ? 'Required' : 'No component-specific flag'}</dd></div><div><dt>Trace ID</dt><dd><code>{record.trace_id ?? 'Not available'}</code></dd></div><div><dt>Span ID</dt><dd><code>{record.span_id ?? 'Not available'}</code></dd></div></dl>{record.warning && <div className="warning"><strong>Warning</strong><span>{record.warning}</span></div>}{record.error && <div className="warning warning--danger" role="alert"><strong>Execution error</strong><span>{record.error}</span></div>}<h3>Evidence references</h3>{evidence.length === 0 ? <p className="muted">No linked evidence was returned for this record.</p> : <div className="agent-evidence">{evidence.map((item) => <article key={item.evidence_id}><strong>{item.signal.replaceAll('_', ' ')}</strong><span>{item.source} · reliability {percent(item.reliability)}</span><code>{String(item.value)}</code></article>)}</div>}<Link className="button button--ghost" to="/command-center#trust-evidence">Open Trust &amp; Evidence</Link>{record.attributes && Object.keys(record.attributes).length > 0 && <><h3>Safe execution attributes</h3><dl>{Object.entries(record.attributes).map(([key, value]) => <div key={key}><dt>{key.replaceAll('.', ' ')}</dt><dd>{String(value)}</dd></div>)}</dl></>}</aside>;
}

export function AgentErrorPanel({ records }: { records: AgentDecision[] }) {
    const issues = records.filter((record) => record.error || record.warning || ['failed', 'skipped'].includes(agentStatus(record)));
    if (issues.length === 0) return <section className="panel agent-errors"><h2>Errors and warnings</h2><p>No execution errors or component warnings were returned.</p></section>;
    return <section className="panel agent-errors"><h2>Errors and warnings</h2>{issues.map((record) => <div className={record.error ? 'warning warning--danger' : 'warning'} key={record.agent}><strong>{agentLabel(record)}</strong><span>{record.error ?? record.warning ?? agentStatus(record)}</span></div>)}</section>;
}

export function PlannedAgentsRoadmap() {
    return <section className="panel planned-agents"><div className="section-heading"><div><span className="eyebrow">Roadmap — separate from execution</span><h2>Planned Capabilities</h2></div></div>{['GIS Analysis Agent', 'Patient Flow Agent', 'Trust Evaluation Agent', 'Incident Commander Agent'].map((name) => <article key={name}><strong>{name}</strong><span>Planned capability — not executed in this simulation.</span></article>)}</section>;
}
