import { lazy, Suspense, useState } from 'react';

import { hospitalOutcomeDiffs, interventionApplicability, normalizeWeights, outcomeAsRun, transferPlanDiff } from '../counterfactualUtils';
import type { CounterfactualExplorerResponse, CounterfactualOutcome, InterventionDefinition, InterventionParameters, MapComparisonMode, RankingWeights } from '../counterfactualTypes';
import type { CompletedRun, Hospital } from '../types';
import { decimal, percent } from '../utils';
import { EmbeddedTraceDashboard } from './EmbeddedTraceDashboard';

const HealthcareMap = lazy(() => import('./HealthcareMap').then((module) => ({ default: module.HealthcareMap })));
const processingStages = ['Loading baseline', 'Validating interventions', 'Applying intervention models', 'Re-evaluating hospital digital twins', 'Recalculating transfer plans', 'Reassessing trust and uncertainty', 'Ranking interventions', 'Publishing telemetry', 'Comparison complete'];

export function CounterfactualProcessingState() {
    return <section className="panel counterfactual-processing" role="status"><span className="eyebrow">Counterfactual processing stages</span><h2>Comparison request in progress</h2><p>These are non-streaming processing stages, not live backend events.</p><ol>{processingStages.map((stage) => <li key={stage}>{stage}</li>)}</ol></section>;
}

export function InterventionSelector({ definitions, run, selected, parameters, onToggle, onParameters, onSelectAll, onClear, onReset, onRun, loading }: { definitions: InterventionDefinition[]; run: CompletedRun; selected: string[]; parameters: Record<string, InterventionParameters>; onToggle: (id: string) => void; onParameters: (id: string, values: InterventionParameters) => void; onSelectAll: () => void; onClear: () => void; onReset: () => void; onRun: () => void; loading: boolean }) {
    const candidates = definitions.filter((definition) => definition.id !== 'no-intervention');
    return <section className="panel intervention-selector"><div className="section-heading"><div><span className="eyebrow">Candidate interventions</span><h2>Intervention Selection</h2></div><div className="button-row"><button type="button" className="button button--ghost" onClick={onSelectAll}>Select applicable</button><button type="button" className="button button--ghost" onClick={onClear}>Clear</button><button type="button" className="button button--ghost" onClick={onReset}>Reset defaults</button></div></div><p className="muted">The no-intervention outcome is always included as the exact simulation baseline.</p><div className="intervention-cards">{candidates.map((definition) => { const applicability = interventionApplicability(definition, run); const checked = selected.includes(definition.id); return <article className={`${checked ? 'intervention-card--selected' : ''} ${!applicability.applicable ? 'intervention-card--disabled' : ''}`} key={definition.id}><label><input type="checkbox" checked={checked} disabled={!applicability.applicable} onChange={() => onToggle(definition.id)} /><span>{definition.category}</span><strong>{definition.name}</strong></label><p>{definition.description}</p><dl><div><dt>Applicability</dt><dd>{applicability.reason}</dd></div><div><dt>Complexity</dt><dd>{definition.complexity}</dd></div><div><dt>Activation delay</dt><dd>{definition.activation_delay_minutes} minutes · synthetic estimate</dd></div><div><dt>Mechanism</dt><dd>{definition.mechanism}</dd></div></dl><details><summary>Safety constraints</summary><ul>{definition.safety_constraints.map((constraint) => <li key={constraint}>{constraint}</li>)}</ul></details>{checked && <InterventionParametersPanel id={definition.id} values={parameters[definition.id] ?? {}} onChange={(values) => onParameters(definition.id, values)} />}</article>; })}</div><div className="button-row"><button type="button" className="button button--primary" disabled={loading || selected.length === 0} onClick={onRun}>{loading ? 'Running comparison…' : `Run ${selected.length} selected counterfactual${selected.length === 1 ? '' : 's'}`}</button><span className="muted small">Duplicate IDs are removed before submission. All candidates require human authorization.</span></div></section>;
}

function NumericParameter({ label, value, min, max, step, unit, onChange }: { label: string; value: number; min: number; max: number; step: number; unit: string; onChange: (value: number) => void }) {
    return <label className="parameter-field"><span>{label}</span><input type="number" value={value} min={min} max={max} step={step} onChange={(event) => onChange(Number(event.target.value))} /><small>{unit}</small></label>;
}

function InterventionParametersPanel({ id, values, onChange }: { id: string; values: InterventionParameters; onChange: (values: InterventionParameters) => void }) {
    if (id === 'network-segmentation') return <div className="parameter-grid"><NumericParameter label="Cyber-loss reduction" value={values.cyber_loss_reduction ?? .65} min={.1} max={.95} step={.05} unit="fraction" onChange={(value) => onChange({ ...values, cyber_loss_reduction: value })} /></div>;
    if (id === 'backup-power-activation') return <div className="parameter-grid"><NumericParameter label="Backup coverage" value={values.backup_capacity_coverage ?? .8} min={.1} max={1} step={.05} unit="fraction" onChange={(value) => onChange({ ...values, backup_capacity_coverage: value })} /><NumericParameter label="Effective duration" value={values.backup_duration_hours ?? 48} min={1} max={168} step={1} unit="hours" onChange={(value) => onChange({ ...values, backup_duration_hours: value })} /></div>;
    if (id === 'regional-surge-capacity') return <div className="parameter-grid"><NumericParameter label="Temporary beds" value={values.added_temporary_beds ?? 120} min={10} max={500} step={10} unit="synthetic beds" onChange={(value) => onChange({ ...values, added_temporary_beds: value })} /><NumericParameter label="Staffing availability" value={values.staffing_availability ?? .8} min={.25} max={1} step={.05} unit="fraction" onChange={(value) => onChange({ ...values, staffing_availability: value })} /></div>;
    if (id === 'ambulance-rerouting') return <div className="parameter-grid"><NumericParameter label="Maximum distance" value={values.maximum_transfer_distance_miles ?? 80} min={5} max={250} step={5} unit="miles" onChange={(value) => onChange({ ...values, maximum_transfer_distance_miles: value })} /><NumericParameter label="Maximum patients" value={values.maximum_transfer_patients ?? 80} min={1} max={500} step={1} unit="simulated patients" onChange={(value) => onChange({ ...values, maximum_transfer_patients: value })} /></div>;
    if (id === 'telemetry-verification') return <div className="parameter-grid"><NumericParameter label="Integrity recovery target" value={values.integrity_recovery_level ?? .9} min={.5} max={1} step={.05} unit="integrity score" onChange={(value) => onChange({ ...values, integrity_recovery_level: value })} /></div>;
    return <p className="small muted">Combined controls use bounded documented defaults; individual effects are applied once.</p>;
}

const metricDefinitions = [
    ['Regional risk', 'regional_risk_score', 'lower'], ['Resilience', 'resilience_score', 'higher'], ['Confidence', 'recommendation_confidence', 'higher'], ['Telemetry integrity', 'telemetry_integrity', 'higher'], ['Critical hospitals', 'critical_hospital_count', 'lower'], ['Unserved demand', 'unserved_demand', 'lower'], ['Transfer patients', 'total_transfer_patients', 'tradeoff'],
] as const;

function outcomeValue(outcome: CounterfactualOutcome, key: typeof metricDefinitions[number][1]) { return outcome[key] ?? null; }
function metricFormat(key: typeof metricDefinitions[number][1], value: number | null) { return value === null ? 'Unavailable' : ['critical_hospital_count', 'unserved_demand', 'total_transfer_patients'].includes(key) ? decimal(value) : percent(value); }

export function OutcomeComparison({ comparison }: { comparison: CounterfactualExplorerResponse }) {
    const outcomes = [comparison.baseline, ...comparison.interventions];
    return <section className="panel comparison-view"><div className="section-heading"><div><span className="eyebrow">Actual counterfactual results</span><h2>Outcome Comparison</h2></div></div><div className="comparison-cards">{outcomes.map((outcome) => <article className={outcome.intervention_id === 'no-intervention' ? 'comparison-card--baseline' : outcome.status === 'failed' ? 'comparison-card--failed' : ''} key={outcome.intervention_id}><span>{outcome.intervention_id === 'no-intervention' ? 'Baseline · No Intervention' : outcome.category}</span><h3>{outcome.intervention_name}</h3>{outcome.status === 'failed' ? <div className="warning warning--danger"><strong>Evaluation failed</strong><span>{outcome.error}</span></div> : <dl>{metricDefinitions.map(([label, key, direction]) => { const value = outcomeValue(outcome, key); const baselineValue = outcomeValue(comparison.baseline, key); const change = value !== null && baselineValue !== null ? value-baselineValue : null; return <div key={key}><dt>{label}<small>{direction === 'tradeoff' ? 'Trade-off metric' : `${direction} is better`}</small></dt><dd>{metricFormat(key, value)}</dd><span>{outcome.intervention_id === 'no-intervention' || change === null ? 'Reference value' : `${change >= 0 ? '+' : ''}${['critical_hospital_count', 'unserved_demand', 'total_transfer_patients'].includes(key) ? decimal(change) : percent(change)} vs baseline`}</span></div>; })}</dl>}</article>)}</div></section>;
}

export function ComparisonCharts({ comparison }: { comparison: CounterfactualExplorerResponse }) {
    const outcomes = [comparison.baseline, ...comparison.interventions.filter((item) => item.status === 'completed')];
    return <section className="panel comparison-charts"><span className="eyebrow">Text-equivalent comparison charts</span><h2>Comparison Charts</h2><div>{metricDefinitions.map(([label, key]) => { const values = outcomes.map((item) => outcomeValue(item, key) ?? 0); const max = Math.max(...values, .001); return <article key={key}><h3>{label}</h3>{outcomes.map((outcome, index) => <div className="comparison-bar" key={outcome.intervention_id}><span>{outcome.intervention_name}</span><div><i style={{ width: `${Math.max(2, values[index]/max*100)}%` }} /></div><strong>{metricFormat(key, values[index])}</strong></div>)}<p className="sr-only">{outcomes.map((outcome, index) => `${outcome.intervention_name}: ${metricFormat(key, values[index])}`).join('. ')}</p></article>; })}</div></section>;
}

export function RankingPanel({ comparison, ranking, weights, onWeight, onReset }: { comparison: CounterfactualExplorerResponse; ranking: CounterfactualExplorerResponse['ranking']; weights: RankingWeights; onWeight: (key: keyof RankingWeights, value: number) => void; onReset: () => void }) {
    const top = ranking[0]; const topOutcome = comparison.interventions.find((item) => item.intervention_id === top?.intervention_id);
    const insufficient = (comparison.baseline.telemetry_integrity ?? 0) < .5 || (topOutcome?.recommendation_confidence ?? 0) < .4;
    return <><section className="panel ranking-weights"><div className="section-heading"><div><span className="eyebrow">Research decision-support ranking</span><h2>Ranking Priorities</h2></div><button type="button" className="button button--ghost" onClick={onReset}>Reset weights</button></div><p>Changing ranking weights changes prioritization, not the simulated outcomes. Weights are normalized automatically.</p><div>{(Object.keys(weights) as Array<keyof RankingWeights>).map((key) => <label key={key}><span>{key.replaceAll('_', ' ')}</span><input type="range" min="0" max="1" step="0.01" value={weights[key]} onChange={(event) => onWeight(key, Number(event.target.value))} /><output>{percent(normalizeWeights(weights)[key])}</output></label>)}</div></section><section className="panel recommendation-panel"><span className="eyebrow">Recommended for authorized human review</span><h2>{insufficient ? 'Insufficient confidence for automated prioritization' : topOutcome?.intervention_name ?? 'No rankable intervention'}</h2>{top && topOutcome ? <><p>{insufficient ? 'Low telemetry integrity or recommendation confidence prevents a strong ranking claim.' : `Highest current research score: ${top.overall_score.toFixed(3)}.`}</p><dl><div><dt>Main benefit</dt><dd>{top.main_benefit}</dd></div><div><dt>Main trade-off</dt><dd>{top.main_trade_off}</dd></div><div><dt>Risk reduction</dt><dd>{percent(topOutcome.absolute_risk_reduction ?? 0)}</dd></div><div><dt>Remaining critical hospitals</dt><dd>{topOutcome.critical_hospital_count}</dd></div><div><dt>Remaining uncertainty</dt><dd>{percent(topOutcome.uncertainty ?? 0)}</dd></div></dl><strong>Suggested next review action</strong><p>{insufficient ? 'Validate evidence quality before reviewing operational trade-offs.' : 'Review safety constraints, hospital effects, and transfer burden before authorization.'}</p></> : <p>No successful safe candidate is available for prioritization.</p>}</section></>;
}

export function TradeOffMatrix({ comparison, ranking }: { comparison: CounterfactualExplorerResponse; ranking: CounterfactualExplorerResponse['ranking'] }) {
    const ranks = new Map(ranking.map((item) => [item.intervention_id, item]));
    return <section className="panel tradeoff-matrix"><h2>Trade-off Matrix</h2><div className="table-scroll"><table><thead><tr><th>Intervention</th><th>Risk reduction</th><th>Resilience</th><th>Critical avoided</th><th>Unserved reduction</th><th>Additional transfers</th><th>Delay</th><th>Complexity</th><th>Confidence</th><th>Human review</th><th>Rank</th></tr></thead><tbody>{comparison.interventions.map((outcome) => <tr key={outcome.intervention_id} className={outcome.status === 'failed' ? 'comparison-row--failed' : ''}><th>{outcome.intervention_name}{outcome.error && <small>{outcome.error}</small>}</th><td>{percent(outcome.absolute_risk_reduction ?? 0)}</td><td>{percent(outcome.resilience_improvement ?? 0)}</td><td>{outcome.critical_hospitals_avoided ?? '—'}</td><td>{decimal(outcome.unserved_demand_reduction ?? 0)}</td><td>{outcome.additional_transfers ?? '—'}</td><td>{outcome.estimated_activation_delay_minutes ?? '—'} min</td><td>{outcome.complexity ?? '—'}</td><td>{percent(outcome.recommendation_confidence ?? 0)}</td><td>{outcome.human_review_required ? 'Required' : 'Not flagged'}</td><td>{ranks.get(outcome.intervention_id)?.rank ?? 'Excluded'}</td></tr>)}</tbody></table></div><p className="disclaimer-inline">More transfers are treated as a burden, not automatically as an improvement. Failed and unsafe outcomes are excluded from ranking.</p></section>;
}

export function HospitalComparison({ comparison, intervention, hospitals, selectedId, onSelect }: { comparison: CounterfactualExplorerResponse; intervention: CounterfactualOutcome; hospitals: Hospital[]; selectedId: string | null; onSelect: (id: string) => void }) {
    const [sort, setSort] = useState('risk-reduction');
    const names = new Map(hospitals.map((hospital) => [hospital.hospital_id, hospital.name]));
    const diffs = hospitalOutcomeDiffs(comparison.baseline, intervention).sort((left, right) => sort === 'remaining-risk' ? right.intervention.disruption_probability-left.intervention.disruption_probability : sort === 'capacity' ? right.capacityChange-left.capacityChange : sort === 'critical' ? Number(right.intervention.status === 'critical')-Number(left.intervention.status === 'critical') : left.riskChange-right.riskChange);
    return <section className="panel hospital-comparison"><div className="section-heading"><div><span className="eyebrow">Non-map spatial equivalent</span><h2>Hospital-Level Impact</h2></div><label>Sort hospitals<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="risk-reduction">Largest risk reduction</option><option value="remaining-risk">Highest remaining risk</option><option value="capacity">Largest capacity improvement</option><option value="critical">Unchanged critical status</option></select></label></div><div className="table-scroll"><table><thead><tr><th>Hospital</th><th>Status transition</th><th>Capacity change</th><th>Demand</th><th>Load ratio</th><th>Risk change</th><th>Cyber loss</th><th>Dependency pressure</th></tr></thead><tbody>{diffs.map((diff) => <tr key={diff.hospitalId} className={`${selectedId === diff.hospitalId ? 'table-row--selected' : ''} difference--${diff.direction}`} tabIndex={0} onClick={() => onSelect(diff.hospitalId)} onKeyDown={(event) => { if (event.key === 'Enter') onSelect(diff.hospitalId); }}><th>{names.get(diff.hospitalId)}<small>{diff.hospitalId}</small></th><td>{diff.statusTransition}</td><td>{diff.capacityChange >= 0 ? '+' : ''}{decimal(diff.capacityChange)}</td><td>{decimal(diff.baseline.estimated_demand)} → {decimal(diff.intervention.estimated_demand)}</td><td>{decimal(diff.baseline.load_ratio)} → {decimal(diff.intervention.load_ratio)}</td><td>{diff.riskChange >= 0 ? '+' : ''}{percent(diff.riskChange)} · {diff.direction}</td><td>{decimal(diff.baseline.cyber_loss)} → {decimal(diff.intervention.cyber_loss)}</td><td>{decimal(diff.baseline.dependency_pressure)} → {decimal(diff.intervention.dependency_pressure)}</td></tr>)}</tbody></table></div></section>;
}

export function TransferComparison({ comparison, intervention, hospitals }: { comparison: CounterfactualExplorerResponse; intervention: CounterfactualOutcome; hospitals: Hospital[] }) {
    const names = new Map(hospitals.map((hospital) => [hospital.hospital_id, hospital.name]));
    const diffs = transferPlanDiff(comparison.baseline.transfer_plan, intervention.transfer_plan);
    return <section className="panel transfer-comparison"><h2>Simulated Transfer Impact</h2>{diffs.length === 0 ? <div className="empty-state">No transfer-route differences were produced.</div> : <div>{diffs.map((diff) => { const transfer = diff.intervention ?? diff.baseline; return <article key={diff.key}><span className={`status ${transfer?.safety_constraints_satisfied ? 'status--stable' : 'status--critical'}`}>{diff.status}</span><strong>{names.get(transfer?.from_hospital_id ?? '')} → {names.get(transfer?.to_hospital_id ?? '')}</strong><span>{diff.patientChange >= 0 ? '+' : ''}{diff.patientChange} simulated patients</span><small>{transfer?.rationale}</small>{!transfer?.safety_constraints_satisfied && <b>Safety constraint warning</b>}</article>; })}</div>}<p className="disclaimer-inline">Routes are synthetic planning estimates and are not authorized transfer decisions.</p></section>;
}

export function CounterfactualMapComparison({ run, comparison, intervention, hospitals, mode, onMode }: { run: CompletedRun; comparison: CounterfactualExplorerResponse; intervention: CounterfactualOutcome; hospitals: Hospital[]; mode: MapComparisonMode; onMode: (mode: MapComparisonMode) => void }) {
    const baselineRun = outcomeAsRun(run, comparison.baseline, 'baseline');
    const interventionRun = outcomeAsRun(run, intervention, mode);
    return <section className="counterfactual-map"><div className="panel map-mode-control"><h2>GIS Comparison Mode</h2><div className="button-row">{(['baseline', 'intervention', 'side-by-side', 'difference'] as MapComparisonMode[]).map((value) => <button type="button" aria-pressed={mode === value} className={`button ${mode === value ? 'button--primary' : 'button--ghost'}`} onClick={() => onMode(value)} key={value}>{value.replaceAll('-', ' ')}</button>)}</div><p>Difference markers: outlined green improves, gray is unchanged, and outlined red deteriorates versus baseline.</p></div><Suspense fallback={<section className="panel map-panel" role="status">Loading comparison map…</section>}>{mode === 'side-by-side' ? <div className="map-side-by-side"><HealthcareMap hospitals={hospitals} run={baselineRun} comparisonLabel="Baseline · synthetic map" /><HealthcareMap hospitals={hospitals} run={interventionRun} comparisonLabel={`${intervention.intervention_name} · synthetic map`} /></div> : <HealthcareMap hospitals={hospitals} run={mode === 'baseline' ? baselineRun : interventionRun} comparisonBaseline={mode === 'difference' ? comparison.baseline.hospital_states : []} comparisonLabel={`${mode} view · simulated estimates`} />}</Suspense></section>;
}

export function CounterfactualObservability({ comparison }: { comparison: CounterfactualExplorerResponse }) {
    const url = import.meta.env.VITE_SIGNOZ_DASHBOARD_URL as string | undefined;
    return <section className="panel"><span className="eyebrow">OpenTelemetry correlation</span><h2>Comparison Observability</h2><dl className="metric-list"><div><dt>Comparison ID</dt><dd><code>{comparison.comparison_id}</code></dd></div><div><dt>Simulation ID</dt><dd><code>{comparison.simulation_id}</code></dd></div><div><dt>Trace ID</dt><dd><code>{comparison.trace_id ?? 'Not exposed while telemetry export is disabled'}</code></dd></div><div><dt>Partial failures</dt><dd>{comparison.incomplete ? 'Yes · review required' : 'None'}</dd></div></dl>{url ? <EmbeddedTraceDashboard simulationId={comparison.simulation_id} traceId={comparison.trace_id} /> : <button type="button" className="button button--ghost" disabled>SigNoz dashboard URL not configured</button>}</section>;
}

export function CounterfactualReport({ run, comparison, ranking }: { run: CompletedRun; comparison: CounterfactualExplorerResponse; ranking: CounterfactualExplorerResponse['ranking'] }) {
    return <section className="panel counterfactual-report" id="comparison-report"><div className="section-heading"><div><span className="eyebrow">Print-friendly research report</span><h2>Comparison Report</h2></div><button type="button" className="button button--ghost no-print" onClick={() => window.print()}>Print comparison report</button></div><p><strong>Scenario:</strong> {run.scenario.name} · <strong>Simulation:</strong> {run.result.simulation_id}</p><p><strong>Baseline risk:</strong> {percent(comparison.baseline.regional_risk_score ?? 0)} · <strong>Interventions compared:</strong> {comparison.interventions.map((item) => item.intervention_name).join(', ')}</p><h3>Research ranking methodology</h3><p>Normalized risk, resilience, demand, critical-hospital, and trust benefits are balanced against transfer burden, delay, complexity, and safety penalties. Weight changes affect prioritization only.</p><ol>{ranking.map((item) => <li key={item.intervention_id}>#{item.rank} {comparison.interventions.find((outcome) => outcome.intervention_id === item.intervention_id)?.intervention_name}: score {item.overall_score.toFixed(3)}, benefit {item.main_benefit}, trade-off {item.main_trade_off}.</li>)}</ol><h3>Limitations</h3><ul>{comparison.limitations.map((item) => <li key={item}>{item}</li>)}</ul><p className="disclaimer-inline">Research decision-support prototype using synthetic data. Counterfactual outcomes are simulated estimates, require authorized human review, and are not clinical, transfer, cybersecurity, or emergency-response instructions.</p></section>;
}
