import type { Hospital, Scenario, SimulationResult } from '../types';
import type { CounterfactualExplorerResponse, InterventionDefinition } from '../counterfactualTypes';

export const hospitals: Hospital[] = [
    { hospital_id: 'HOSP-DFW-001', name: 'North Regional Medical Center', latitude: 32.9, longitude: -97.2, staffed_beds: 310, icu_beds: 42, baseline_occupancy: 0.78, cyber_readiness: 0.82, backup_power_hours: 72, referral_neighbors: ['HOSP-DFW-002'], critical_dependencies: ['GRID-NORTH'] },
    { hospital_id: 'HOSP-DFW-002', name: 'Central Community Hospital', latitude: 32.82, longitude: -97.0, staffed_beds: 220, icu_beds: 28, baseline_occupancy: 0.84, cyber_readiness: 0.56, backup_power_hours: 36, referral_neighbors: ['HOSP-DFW-001'], critical_dependencies: ['GRID-CENTRAL'] },
];

const request = (scenario_name: string, severity: number) => ({ scenario_name, horizon_hours: 24, demand_multiplier: 1.35, hazard: { heat_index: 112, flood_severity: 0.1, air_quality_index: 155, grid_outage_probability: 0.35 }, cyber_event: { target_hospital_id: 'HOSP-DFW-001', severity, attack_type: 'ransomware', telemetry_tampering: 0.2 }, missing_telemetry_ratio: 0.1, enable_counterfactuals: true });

export const scenarios: Scenario[] = [
    { id: 'flood-grid-cascade', name: 'Flood Grid Cascade', category: 'infrastructure', description: 'Flood scenario', tags: ['flood'], severity: 'high', request: request('flood-grid-cascade', 0.25) },
    { id: 'heatwave-ransomware', name: 'Heatwave Ransomware', category: 'cyber-physical', description: 'Heatwave scenario', tags: ['heatwave', 'cyber'], severity: 'critical', request: request('heatwave-ransomware', 0.85) },
    { id: 'wildfire-telemetry', name: 'Wildfire + Telemetry Tampering', category: 'trust', description: 'Wildfire scenario', tags: ['wildfire', 'trust'], severity: 'medium', request: request('wildfire-telemetry', 0.55) },
];

export function result(overrides: Partial<SimulationResult> = {}): SimulationResult {
    return {
        simulation_id: 'sim-123', scenario_name: 'flood-grid-cascade', regional_risk_score: 0.58, resilience_score: 0.39,
        affected_hospitals: [{ hospital_id: 'HOSP-DFW-001', effective_capacity: 240, estimated_demand: 280, load_ratio: 1.17, cyber_loss: 0.12, hazard_pressure: 0.48, dependency_pressure: 0.2, disruption_probability: 0.72, status: 'degraded' }],
        transfer_plan: [], evidence: [{ evidence_id: 'telemetry-integrity', source: 'telemetry-integrity-agent', source_name: 'Rule-based telemetry integrity check', source_type: 'agent-derived evidence', signal: 'telemetry_integrity', value: 0.39, unit: 'score', reliability: 0.39, confidence: .39, integrity_status: 'suspected-tampering', provenance_status: 'basic-lineage', freshness_status: 'current', observed_at: '2026-07-19T00:00:00Z', received_at: '2026-07-19T00:00:00Z', age_seconds: 0, location_scope: 'synthetic region', scenario_id: 'flood-grid-cascade', agent_ids: ['telemetry-integrity-agent', 'meta-orchestrator'], warning: 'Scenario parameters indicate possible telemetry manipulation.', parent_evidence_ids: [], validation_checks: ['tampering-flag-check'] }, { evidence_id: 'regional-risk', source: 'digital-twin', source_name: 'Synthetic regional digital twin', source_type: 'agent-derived evidence', signal: 'regional_risk', value: 0.58, unit: 'probability', reliability: 0.45, integrity_status: 'degraded', provenance_status: 'basic-lineage', freshness_status: 'current', hospital_id: 'HOSP-DFW-001', scenario_id: 'flood-grid-cascade', agent_ids: ['compound-event-detector', 'resilience-planning-agent'], warning: 'Weak supporting evidence.', parent_evidence_ids: ['telemetry-integrity'], validation_checks: ['digital-twin-bounds-check'] }],
        agent_decisions: [
            { agent: 'compound-event-detector', agent_id: 'compound-event-detector', agent_name: 'Compound Event Detector', component_type: 'agent', purpose: 'Detect compound events.', stage: 'detection', status: 'warning', sequence: 1, action: 'escalate', confidence: 0.88, explanation: 'Joint pressure requires escalation.', evidence_ids: ['regional-risk'], duration_ms: 0.41, human_review_required: false, warning: 'Elevated simulated conditions require authorized review.', trace_id: 'abcdef1234567890abcdef1234567890', span_id: '1111111111111111', attributes: { 'scenario.name': 'flood-grid-cascade' } },
            { agent: 'telemetry-integrity-agent', agent_id: 'telemetry-integrity-agent', agent_name: 'Telemetry Integrity Agent', component_type: 'agent', purpose: 'Assess telemetry provenance.', stage: 'security-assessment', status: 'human-review-required', sequence: 2, action: 'quarantine-and-require-human-review', confidence: 0.61, explanation: 'Telemetry integrity requires review.', evidence_ids: ['telemetry-integrity'], duration_ms: 0.72, human_review_required: true, warning: 'Telemetry evidence requires authorized human review.', trace_id: 'abcdef1234567890abcdef1234567890', span_id: '2222222222222222', attributes: { 'scenario.name': 'flood-grid-cascade' } },
            { agent: 'resilience-planning-agent', agent_id: 'resilience-planning-agent', agent_name: 'Resilience Planning Agent', component_type: 'agent', purpose: 'Recommend bounded planning actions.', stage: 'planning', status: 'warning', sequence: 3, action: 'activate-regional-load-balancing', confidence: 0.45, explanation: 'Regional load balancing requires review.', evidence_ids: ['regional-risk'], duration_ms: 0.96, human_review_required: true, warning: 'Elevated simulated conditions require authorized review.', trace_id: 'abcdef1234567890abcdef1234567890', span_id: '3333333333333333', attributes: { 'scenario.name': 'flood-grid-cascade' } },
            { agent: 'meta-orchestrator', agent_id: 'meta-orchestrator', agent_name: 'Response Orchestrator', component_type: 'system', purpose: 'Assemble a bounded response.', stage: 'response-assembly', status: 'completed', sequence: 4, action: 'coordinate-validated-response', confidence: 0.65, explanation: 'The system assembled reviewed outputs.', evidence_ids: ['regional-risk', 'telemetry-integrity'], duration_ms: null, human_review_required: true },
        ],
        counterfactuals: [{ intervention: 'segment network', regional_risk_score: 0.5, risk_reduction: 0.08 }, { intervention: 'combined containment', regional_risk_score: 0.4, risk_reduction: 0.18 }],
        explanation: 'Backend simulation explanation.', trust: { evidence_completeness: 0.9, telemetry_integrity: 0.39, uncertainty: 0.42, geographic_coverage: .5, policy_compliance: false, recommendation_confidence: 0.45, human_review_required: true, trust_score: .51, evidence_reliability: .42, provenance_strength: 1, freshness_score: 1, consistency_score: .55, calculation_version: 'geotwin-trust-v2.0', factor_contributions: [{ factor: 'telemetry_integrity', raw_value: .39, normalized_value: .39, weight: .22, weighted_contribution: .0858, status: 'warning', explanation: 'Rule-based missing and tampering indicators.', supporting_evidence_count: 2, warning_count: 2 }, { factor: 'uncertainty_penalty', raw_value: .42, normalized_value: .42, weight: -.2, weighted_contribution: -.084, status: 'warning', explanation: 'Conservative uncertainty penalty.', supporting_evidence_count: 2, warning_count: 2 }], review_reasons: [{ code: 'SUSPECTED_TAMPERING', explanation: 'Scenario telemetry contains a material tampering indicator.', severity: 'critical', affected_component: 'HOSP-DFW-001', recommended_action: 'Require data-quality review.' }], warnings: ['Possible telemetry manipulation.'], failed_checks: ['tampering-constraint'], passed_checks: ['synthetic-data-only'], improvement_actions: [{ action: 'Verify telemetry against a secondary source', trigger: 'Suspected tampering', affected_evidence_ids: ['telemetry-integrity'], expected_effect: 'May improve integrity after validation.', priority: 'high', suggested_role: 'Cybersecurity incident lead', resimulation_recommended: true }], policy_checks: [{ policy_id: 'tampering-constraint', name: 'No action under suspected tampering', status: 'failed', explanation: 'Human validation is required.', related_evidence_ids: ['telemetry-integrity'], related_agent_id: 'telemetry-integrity-agent', required_action: 'Validate a secondary source.' }], anomalies: [{ anomaly_type: 'suspected-tampering', severity: 'critical', evidence_ids: ['telemetry-integrity'], explanation: 'Rule-based flag detected.', trust_impact: 'Reduces integrity.', affected_agent_ids: ['telemetry-integrity-agent'], required_action: 'Validate evidence.' }] }, trace_id: 'abcdef1234567890abcdef1234567890', duration_ms: 4.2,
        ...overrides,
    };
}

export const interventionDefinitions: InterventionDefinition[] = [
    { id: 'no-intervention', name: 'No Intervention', category: 'baseline', description: 'Baseline', affected_parameters: [], applicable_scenarios: ['all'], mechanism: 'No transformation', complexity: 'low', activation_delay_minutes: 0, safety_constraints: ['Baseline only'], human_authorization_required: true, executable: true },
    { id: 'network-segmentation', name: 'Network Segmentation', category: 'cyber', description: 'Reduce modeled cyber loss.', affected_parameters: ['cyber severity'], applicable_scenarios: ['all'], mechanism: 'Reduce attack severity.', complexity: 'moderate', activation_delay_minutes: 20, safety_constraints: ['Preserve emergency communications'], human_authorization_required: true, executable: true },
    { id: 'backup-power-activation', name: 'Backup Power Activation', category: 'infrastructure', description: 'Reduce grid exposure.', affected_parameters: ['grid exposure'], applicable_scenarios: ['flood'], mechanism: 'Reduce outage pressure.', complexity: 'moderate', activation_delay_minutes: 15, safety_constraints: ['Fuel availability'], human_authorization_required: true, executable: true },
    { id: 'regional-surge-capacity', name: 'Regional Surge Capacity', category: 'capacity', description: 'Add staffed capacity.', affected_parameters: ['capacity'], applicable_scenarios: ['all'], mechanism: 'Increase capacity.', complexity: 'high', activation_delay_minutes: 90, safety_constraints: ['Staffing'], human_authorization_required: true, executable: true },
    { id: 'ambulance-rerouting', name: 'Ambulance Rerouting', category: 'transport', description: 'Redistribute demand.', affected_parameters: ['demand'], applicable_scenarios: ['all'], mechanism: 'Demand offsets.', complexity: 'moderate', activation_delay_minutes: 10, safety_constraints: ['Destination capacity'], human_authorization_required: true, executable: true },
    { id: 'telemetry-verification', name: 'Telemetry Verification', category: 'telemetry', description: 'Improve modeled integrity.', affected_parameters: ['integrity'], applicable_scenarios: ['wildfire'], mechanism: 'Verify telemetry.', complexity: 'low', activation_delay_minutes: 30, safety_constraints: ['Preserve provenance'], human_authorization_required: true, executable: true },
    { id: 'combined-intervention', name: 'Combined Intervention', category: 'combined', description: 'Apply compatible controls.', affected_parameters: ['cyber', 'grid', 'capacity', 'integrity'], applicable_scenarios: ['all'], mechanism: 'Compose once.', complexity: 'high', activation_delay_minutes: 120, safety_constraints: ['Cross-team approval'], human_authorization_required: true, executable: true },
];

export function comparison(overrides: Partial<CounterfactualExplorerResponse> = {}): CounterfactualExplorerResponse {
    const baselineState = result().affected_hospitals[0];
    const networkState = { ...baselineState, effective_capacity: 252, load_ratio: 1.11, cyber_loss: .04, disruption_probability: .58, status: 'degraded' as const };
    const surgeState = { ...baselineState, effective_capacity: 290, load_ratio: .97, disruption_probability: .34, status: 'stable' as const };
    const baseline = { intervention_id: 'no-intervention', intervention_name: 'No Intervention / Baseline', category: 'baseline', status: 'completed' as const, regional_risk_score: .58, resilience_score: .39, recommendation_confidence: .45, telemetry_integrity: .39, uncertainty: .42, evidence_completeness: .9, critical_hospital_count: 0, degraded_hospital_count: 1, unserved_demand: 40, total_transfer_patients: 0, estimated_operational_cost: 'No incremental modeled activation cost', estimated_activation_delay_minutes: 0, complexity: 'low', human_review_required: true, transfer_plan_safe: true, hospital_states: [baselineState], transfer_plan: [], trade_offs: ['Preserves disruption.'], warnings: [], evaluated_by: 'digital-twin-system', ranked_by: 'counterfactual-ranking-system' };
    const network = { ...baseline, intervention_id: 'network-segmentation', intervention_name: 'Network Segmentation', category: 'cyber', regional_risk_score: .47, resilience_score: .52, recommendation_confidence: .5, critical_hospital_count: 0, unserved_demand: 28, estimated_activation_delay_minutes: 20, complexity: 'moderate', hospital_states: [networkState], absolute_risk_reduction: .11, relative_risk_reduction: .19, resilience_improvement: .13, critical_hospitals_avoided: 0, unserved_demand_reduction: 12, additional_transfers: 0, confidence_change: .05, trade_offs: ['Coordination overhead.'] };
    const surgeTransfer = { from_hospital_id: 'HOSP-DFW-001', to_hospital_id: 'HOSP-DFW-002', patients: 8, rationale: 'Synthetic spare capacity', safety_constraints_satisfied: true };
    const surge = { ...baseline, intervention_id: 'regional-surge-capacity', intervention_name: 'Regional Surge Capacity', category: 'capacity', regional_risk_score: .34, resilience_score: .67, recommendation_confidence: .44, unserved_demand: 6, total_transfer_patients: 8, estimated_activation_delay_minutes: 90, complexity: 'high', hospital_states: [surgeState], transfer_plan: [surgeTransfer], absolute_risk_reduction: .24, relative_risk_reduction: .414, resilience_improvement: .28, critical_hospitals_avoided: 0, unserved_demand_reduction: 34, additional_transfers: 8, confidence_change: -.01, trade_offs: ['High staffing burden.'] };
    return { comparison_id: 'comparison-123', simulation_id: 'sim-123', scenario_name: 'flood-grid-cascade', created_at: '2026-07-18T00:00:00Z', baseline, interventions: [network, surge], ranking: [{ rank: 1, intervention_id: 'regional-surge-capacity', overall_score: .31, main_benefit: 'risk', main_trade_off: 'speed', confidence: .44, explanation: 'Transparent ranking.' }, { rank: 2, intervention_id: 'network-segmentation', overall_score: .18, main_benefit: 'trust', main_trade_off: 'complexity', confidence: .5, explanation: 'Transparent ranking.' }], recommendation: { intervention_id: null, label: 'Insufficient confidence for automated prioritization', rationale: 'Low telemetry integrity.', suggested_review_action: 'Validate evidence.', insufficient_confidence: true, human_review_required: true }, default_ranking_weights: { risk: .28, resilience: .16, demand: .14, critical_hospitals: .1, trust: .12, transfer_burden: .07, speed: .06, complexity: .04, safety: .03 }, trace_id: null, incomplete: false, warnings: [], limitations: ['Synthetic deterministic estimates.'], ...overrides };
}
