from app.models.domain import Hospital

HOSPITALS = [
    Hospital(
        hospital_id="HOSP-DFW-001",
        name="North Regional Medical Center",
        latitude=32.998,
        longitude=-97.235,
        staffed_beds=310,
        icu_beds=42,
        baseline_occupancy=0.78,
        cyber_readiness=0.82,
        backup_power_hours=72,
        referral_neighbors=["HOSP-DFW-002", "HOSP-DFW-003"],
        critical_dependencies=["GRID-NORTH", "EMS-NORTH"],
    ),
    Hospital(
        hospital_id="HOSP-DFW-002",
        name="Central Community Hospital",
        latitude=32.902,
        longitude=-97.041,
        staffed_beds=220,
        icu_beds=28,
        baseline_occupancy=0.84,
        cyber_readiness=0.56,
        backup_power_hours=36,
        referral_neighbors=["HOSP-DFW-001", "HOSP-DFW-004"],
        critical_dependencies=["GRID-CENTRAL", "LAB-REGIONAL"],
    ),
    Hospital(
        hospital_id="HOSP-DFW-003",
        name="Westlake Emergency Institute",
        latitude=32.991,
        longitude=-97.195,
        staffed_beds=180,
        icu_beds=25,
        baseline_occupancy=0.71,
        cyber_readiness=0.76,
        backup_power_hours=48,
        referral_neighbors=["HOSP-DFW-001", "HOSP-DFW-004"],
        critical_dependencies=["GRID-NORTH", "EMS-WEST"],
    ),
    Hospital(
        hospital_id="HOSP-DFW-004",
        name="South Metro Health Center",
        latitude=32.735,
        longitude=-96.998,
        staffed_beds=260,
        icu_beds=35,
        baseline_occupancy=0.81,
        cyber_readiness=0.68,
        backup_power_hours=60,
        referral_neighbors=["HOSP-DFW-002", "HOSP-DFW-003", "HOSP-DFW-005"],
        critical_dependencies=["GRID-SOUTH", "LAB-REGIONAL"],
    ),
    Hospital(
        hospital_id="HOSP-DFW-005",
        name="East County Medical Campus",
        latitude=32.812,
        longitude=-96.612,
        staffed_beds=150,
        icu_beds=18,
        baseline_occupancy=0.69,
        cyber_readiness=0.74,
        backup_power_hours=30,
        referral_neighbors=["HOSP-DFW-004"],
        critical_dependencies=["GRID-EAST", "EMS-EAST"],
    ),
]


def hospital_map() -> dict[str, Hospital]:
    return {hospital.hospital_id: hospital for hospital in HOSPITALS}
